# Generated by Django 4.2.7 on 2023-11-30 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0002_student_delete_member"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estudiante",
            fields=[
                ("idEstudiante", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=255)),
                ("apellidoPaterno", models.CharField(max_length=255)),
                ("apellidoMaterno", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Profesores",
            fields=[
                ("idProfesor", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=255)),
                ("apellidoPaterno", models.CharField(max_length=255)),
                ("apellidoMaterno", models.CharField(max_length=255)),
                ("fechaContratacion", models.DateField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="student",
            name="joined_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone",
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name="Materias",
            fields=[
                ("idMateria", models.AutoField(primary_key=True, serialize=False)),
                ("nombreMateria", models.CharField(max_length=255)),
                ("horario", models.CharField(max_length=255)),
                ("creditos", models.IntegerField()),
                (
                    "idProfesor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.profesores",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inscripciones",
            fields=[
                ("idInscripcion", models.AutoField(primary_key=True, serialize=False)),
                ("costo", models.IntegerField()),
                (
                    "idEstudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.estudiante",
                    ),
                ),
                (
                    "idMateria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.materias",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Eventos",
            fields=[
                ("idEvento", models.AutoField(primary_key=True, serialize=False)),
                ("tituloEvento", models.CharField(max_length=255)),
                ("dia", models.DateField(null=True)),
                ("hora", models.TimeField(null=True)),
                ("lugar", models.CharField(max_length=255)),
                (
                    "idProfesor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.profesores",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Calificaciones",
            fields=[
                ("idCalificacion", models.AutoField(primary_key=True, serialize=False)),
                ("parcial", models.IntegerField()),
                ("calificacion", models.IntegerField()),
                (
                    "idInscripcion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.inscripciones",
                    ),
                ),
            ],
        ),
    ]
